name: research-assistant
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pip
  - pip:
      - bibtexparser
      - faiss-cpu
      - tiktoken
      - openai>=1.0.0
      - tqdm
      - streamlit
      - python-dotenv
      - watchdog
      - pybtex
