name: research-assistant
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - biopython
  - faiss-cpu
  - yagmail  # For Gmail-based SMTP (easy email sending)
  - pytest
  - pip
  - pip:
      - bibtexparser
      - tiktoken
      - openai>=1.0.0
      - tqdm
      - streamlit
      - python-dotenv
      - watchdog
      - pybtex
